version: '3.1'

services:
  example:
    container_name: oauth_govbr
    image: webdevops/php-apache-dev:8.0
    working_dir: /app

    volumes:
      - .:/app
    ports:
      - 80:80
      - 443:443